import csv
import re
from pathlib import Path

INPUT = Path(__file__).parent / "college.csv"
OUTPUT_GO = Path(__file__).parent / "college_data.go"


def clean_name(s: str) -> str:
    if s is None: # type: ignore
        return ""
    s = s.strip()
    # remove any "(Id: ...)" occurrences (covers both U- and C- and different formats)
    s = re.sub(r'\s*\(Id:\s*[^)]+\)', '', s)
    # remove surrounding quotes if any left
    s = s.strip('"').strip()
    return s


def to_go_quoted(s: str) -> str:
    # escape backslashes and double quotes for Go string literal
    return s.replace('\\', '\\\\').replace('"', '\\"')


def main():
    from typing import Dict
    uni_map: Dict[str, list[str]] = {}  # uni -> list(colleges)
    if not INPUT.exists():
        print(f"input file not found: {INPUT}")
        return

    with INPUT.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.reader(fh)
        for i, row in enumerate(reader):
            # skip header row if present
            if i == 0:
                # basic header detection
                if len(row) >= 2 and ("University" in row[0] or "University" in row[1] or "College" in row[0]):
                    continue
            if not row:
                continue
            # guard: some rows might have more columns due to unescaped commas; treat first two as uni and college
            uni_raw = row[0]
            college_raw = row[1] if len(row) > 1 else ""
            uni = clean_name(uni_raw)
            college = clean_name(college_raw)
            if not uni:
                continue
            uni_map.setdefault(uni, [])
            if college:
                uni_map[uni].append(college)

    # sort universities and college lists
    universities = sorted(uni_map.keys())
    for uni in universities:
        uni_map[uni] = sorted(uni_map[uni])

    # write Go file
    lines: list[str] = []
    lines.append("// Code generated by csv_cleaner.py — DO NOT EDIT\n")
    lines.append("package data\n\n")
    # Universities slice
    lines.append("var Universities = []string{\n")
    for u in universities:
        lines.append(f'    "{to_go_quoted(u)}",\n')
    lines.append("}\n\n")
    # Uni -> colleges map
    lines.append("var UniColleges = map[string][]string{\n")
    for u in universities:
        lines.append(f'    "{to_go_quoted(u)}": {{\n')
        for c in uni_map[u]:
            lines.append(f'        "{to_go_quoted(c)}",\n')
        lines.append("    },\n")
    lines.append("}\n")

    OUTPUT_GO.write_text("".join(lines), encoding="utf-8")
    print(f"wrote go data to {OUTPUT_GO} ({len(universities)} universities)")


if __name__ == "__main__":
    main()